name: Start build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Publish to maven repo
        run: ./gradlew publishPluginMavenPublicationToGitHubPackagesRepository
        env:
          USER_CI: ${{ secrets.USER_CI }}
          TOKEN_CI: ${{ secrets.TOKEN_CI }}